#lang s-exp phc-adt/declarations
(remembered! tagged-structure (untagged a b))
(remembered! tagged-structure (st2 a b))
(remembered! tagged-structure (t a b c))
(remembered! tagged-structure (tabc a b c))
(remembered! tagged-structure (tag1 values))
(remembered! tagged-structure (a values))
(remembered! tagged-structure (b values))
(remembered! tagged-structure (c values))
(remembered! tagged-structure (d values))
(remembered! tagged-structure (e values))
(remembered! tagged-structure (F values))
(remembered! tagged-structure (tag0 values))
(remembered! tagged-structure (tag2 values))
(remembered! tagged-structure (tag3 values))
(remembered! tagged-structure (tagged-s1))
(remembered! tagged-structure (tagged-s2 f g))
(remembered! tagged-structure (tagged-s3 f g))
(remembered! tagged-structure (tagged-s4 f g))
(remembered! tagged-structure (c1 values))
(remembered! tagged-structure (c2 values))
(remembered! tagged-structure (c3 values))
(remembered! tagged-structure (txyz a b))
(remembered! tagged-structure (cxyz values))
(remembered! tagged-structure (txyz x y))
(remembered! tagged-structure (untagged))
(remembered! tagged-structure (empty-tg))
(remembered! tagged-structure (empty-ct values))
(remembered! tagged-structure (empty-ct-t2 values))
(remembered! tagged-structure (empty-ct-t3 values))
(remembered! tagged-structure (empty-ct-2 values))
(remembered! tagged-structure (empty-ct-3 values))
(remembered! tagged-structure (untagged test-fa test-fb))
(remembered! tagged-structure (untagged test-fa test-fc))
(remembered! tagged-structure (untagged test-fa test-fd))
(remembered! tagged-structure (untagged a c))
(remembered! tagged-structure (untagged a b c d))
(remembered! tagged-structure (untagged a b c y))
(remembered! tagged-structure (untagged a b c))
(remembered! tagged-structure (untagged a))
(remembered! tagged-structure (t0 tagged-fa tagged-fb tagged-fc))
(remembered! tagged-structure (t0 tagged-fx tagged-fy tagged-fz))
(remembered! tagged-structure (a a b))
(remembered! tagged-structure (b a b))
(remembered! tagged-structure (c a b))
(remembered! tagged-structure (ma faa fab fav))
(remembered! tagged-structure (mb fba fbv))
(remembered! tagged-structure (t1 x y))
(remembered! tagged-structure (foo x y z))
(remembered! tagged-structure (x values))
(remembered! tagged-structure (y values))
(remembered! tagged-structure (z values))
(remembered! tagged-structure (w values))
(remembered! tagged-structure (tg x y))
