#lang s-exp phc-adt/declarations
(remembered! tagged-structure (foo a b c))
(remembered! tagged-structure (tag b))
(remembered! tagged-structure (foo b))
(remembered! tagged-structure (foo a c))
(remembered! tagged-structure (bar a b c))
(remembered! tagged-structure (baz a b))
(remembered! tagged-structure (qux b d))
(remembered! tagged-structure (bar a c))
(remembered! tagged-structure (baz a))
(remembered! tagged-structure (qux d))
(remembered! tagged-structure (bar b))
(remembered! tagged-structure (baz b))
(remembered! tagged-structure (qux b))
(remembered! tagged-structure (foo d))
(remembered! tagged-structure (foo a))
(remembered! tagged-structure (foo a b))
(remembered! tagged-structure (foo a))
(remembered! tagged-structure (foo a b))
(remembered! tagged-structure (foo b d))
(remembered! tagged-structure (foo a b d))
(remembered! tagged-structure (foo a b c d))
(remembered! tagged-structure (foo a d))
(remembered! tagged-structure (foo a c d))
